### ISSUE TITLE
Setup a linter (JSHint) for the entire translators repo

### ISSUE THREAD

**Issue by sanjaiganesh** [openT2T/translators#38]

**Comment by jasongin** [comment]
Also consider ESLint, which seems to be more modern and configurable.
There are lots of comparisons on the web, [here's one](https://www.sitepoint.com/comparison-javascript-linting-tools/).

**Comment by tjaffri** [comment]
Also, we should consider a very simple travis rule to run the linter on every commit that comes in, and only merge commits that pass. We can later extend the travis rule to add other tests, but for now linting should suffice. Travis is free for open source projects like ours.

**Comment by jasongin** [comment]
> We can later extend the travis rule to add other tests

Yes! Validations I've been thinking of include:
* Validate interface XML files conform to schema (XSD)
* Validate opent2t metadata in package.json
* Validate dependencies in package.json (for interface/onboarding references to other packages)
* Validate interface modules successfully load and export their interface
* Validate translators implement interfaces declared in metadata
* Validate translator interface method implementations have correct parameters/return types

Most of this tooling probably belongs in the CLI repo, because it should be possible to run these validations manually during development.
