### ISSUE TITLE
Allow translators to return current device state 

### ISSUE THREAD

**Issue by busadave13** [openT2T/translators#41]
Translators do not support getting the current device state without making multiple calls to the translator for each property. Should consider adding support to translators that allow getting the current state of the device in a single call

**Comment by jasongin** [comment]
This is related to the capability of batching requests for multiple properties. It also relates to OCF alignment, because OCF includes a way to get and set multiple (or all) properties at the same time.

**Comment by tjaffri** [comment]
@busadave13 this is fixed in the dev branch for the Wink Thermostat translator... let me know if you disagree (specifically you can call get on the RAML schema method to get the entire device state).

We are copying this pattern in all other translators so closing this for now. If you disagree please reopen.
